name: CI Pipeline

on:
  push:
    branches: [ bishesna_practical_task ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_REGISTRY: docker.io
  BACKEND_IMAGE: bishesna/node-backend
  FRONTEND_IMAGE: bishesna/some-content-nginx

jobs:
  build-and push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  
    